//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.18 at 05:50:42 PM ICT 
//


package com.sma.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="paymentTransactionNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="callbackData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="errorDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paymentTransactionNumber",
    "callbackData",
    "errorDesc"
})
@XmlRootElement(name = "FailurePaymentRequest")
public class FailurePaymentRequest {

    @XmlElement(required = true)
    protected String paymentTransactionNumber;
    @XmlElement(required = true)
    protected String callbackData;
    @XmlElement(required = true)
    protected String errorDesc;

    /**
     * Gets the value of the paymentTransactionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTransactionNumber() {
        return paymentTransactionNumber;
    }

    /**
     * Sets the value of the paymentTransactionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTransactionNumber(String value) {
        this.paymentTransactionNumber = value;
    }

    /**
     * Gets the value of the callbackData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallbackData() {
        return callbackData;
    }

    /**
     * Sets the value of the callbackData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallbackData(String value) {
        this.callbackData = value;
    }

    /**
     * Gets the value of the errorDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorDesc() {
        return errorDesc;
    }

    /**
     * Sets the value of the errorDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorDesc(String value) {
        this.errorDesc = value;
    }

}
